/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ssan_CONSTANTS_H
#define ssan_CONSTANTS_H

#include "ssan_types.h"

namespace ssan {

class ssanConstants {
 public:
  ssanConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const ssanConstants g_ssan_constants;

} // namespace

#endif
