/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lvyahui.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.lvyahui.struts.form.HelloForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-04-2014
 * 
 * XDoclet definition:
 * @struts.action path="/hello" name="helloForm" input="/hellostruts.jsp" scope="request" validate="true"
 */
public class HelloAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HelloForm helloForm = (HelloForm) form;// TODO Auto-generated method stub
		String info = helloForm.getInfo();		//所有的输入内容从ActionForm中取得
		if(info.length()>15){		//数据长度过长 
			ActionMessages errors = new ActionMessages();
			errors.add("info",new ActionMessage("msg.info"));
			//super.saveErrors(request, errors);//保存错误信息
			super.saveMessages(request, errors);//不能输出信息量了
			return mapping.getInputForward();//取得错误页地址
		}else{
			request.setAttribute("msg", info);		//将信息设置在request属性范围中
			//在Action之中，如果想要跳转，不要配置，在struts-config.xml文件
			return mapping.findForward("show");		//此处返回的是一个映射的路径，以后想要修改跳转，只要修改配置文件
		}
	}
}